name: font_awesome
description: The iconic font and CSS framework
version: 4.7.0
homepage: https://github.com/luisvt/Font-Awesome
environment:
  sdk: ">=1.19.0 <2.0.0"
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Dave Gandy <dave@fontawesome.io>
license: (OFL-1.1 AND MIT)